#!/bin/sh -e

install -D -m0644 files/awk/wscanparse.awk /usr/share/wifish/wscanparse.awk
install -D -m0644 files/awk/wlistparse.awk /usr/share/wifish/wlistparse.awk
install -D -m0644 files/awk/wscan2menu.awk /usr/share/wifish/wscan2menu.awk
install -D -m0644 files/awk/iwparse.awk /usr/share/wifish/iwparse.awk
install -D -m0755 wifish /usr/bin
if [ ! -d /etc/sv/wpa_supplicant ];then
	echo "Installing /etc/sv/wpa_supplicant service"
	install -D -d -m0755 /etc/sv/wpa_supplicant
	install -D -m0644 files/wpa_supplicant/conf /etc/sv/wpa_supplicant/conf
	install -D -m0755 files/wpa_supplicant/run /etc/sv/wpa_supplicant/run
	install -D -m0755 files/wpa_supplicant/log/run /etc/sv/wpa_supplicant/log/run
fi
